"""record which clue an answer gave away

Revision ID: 15363a0df386
Revises: ab7e3c9067ab
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '15363a0df386'
down_revision: str | None = 'ab7e3c9067ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('clue_revealed', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'clue_revealed')
    # ### end Alembic commands ###
