"""record what a suspect claimed

Revision ID: ab7e3c9067ab
Revises: d42e8b3a2e52
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ab7e3c9067ab'
down_revision: str | None = 'd42e8b3a2e52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('claimed_room', sa.String(length=32), nullable=True))
    op.add_column('statements', sa.Column('claimed_interval', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'claimed_interval')
    op.drop_column('statements', 'claimed_room')
    # ### end Alembic commands ###
