"""record how a question was classified

Revision ID: d42e8b3a2e52
Revises: 0f90e37c4ebe
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd42e8b3a2e52'
down_revision: str | None = '0f90e37c4ebe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('intent', sa.String(length=16), server_default='question', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'intent')
    # ### end Alembic commands ###
