"""record the accusation that ended a match

Revision ID: ecc6ce9e9e22
Revises: 15363a0df386
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ecc6ce9e9e22'
down_revision: str | None = '15363a0df386'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('accused_culprit', sa.String(length=32), nullable=True))
    op.add_column('matches', sa.Column('accused_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'accused_evidence')
    op.drop_column('matches', 'accused_culprit')
    # ### end Alembic commands ###
