/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Whether the process is up. Deliberately does not touch the database:
         *     readiness with dependencies arrives with the schema (phase 1).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a match */
        post: operations["create_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The notebook */
        get: operations["read_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/accusation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Name a culprit and end the match
         * @description No model is involved. The outcome is arithmetic (RN-032).
         */
        post: operations["accuse_matches__match_id__accusation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/accusation/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read an accusation out of prose
         * @description Fills the form; commits nothing.
         *
         *     The player confirms by posting the fields to `/accusation`. That endpoint
         *     accepts no prose, so a misreading cannot become an accusation without
         *     somebody seeing it first (RN-031).
         */
        post: operations["draft_accusation_matches__match_id__accusation_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/confrontations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show a suspect a piece of evidence
         * @description Costs two turns, and only the evidence the player already holds.
         */
        post: operations["take_confrontation_matches__match_id__confrontations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The whole record of a finished match
         * @description Every turn in order, the stances, the evidence, and the verdict.
         *
         *     Only once the match is over, and that is the whole reason it may show the
         *     bookkeeping — `lied`, which fact an answer leaned on, what a rejected turn
         *     was rejected for. Offered mid-match the same payload would be a lie
         *     detector and end the game on turn one, so it is a 409 until there is
         *     nothing left to spoil (RN-035).
         */
        get: operations["review_matches__match_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{match_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Question a suspect */
        post: operations["take_turn_matches__match_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccusationText
         * @description What a player typed, before it is a form.
         */
        AccusationText: {
            /** Text */
            text: string;
        };
        /**
         * Answer
         * @description What came back, and what it cost.
         *
         *     `answered` is false when a reply was produced and then discarded — by the
         *     output filters, or by the provider declining. The turn is spent, because the
         *     player had their go.
         *
         *     An unreachable model is not this shape: it is a 503 and costs nothing.
         *
         *     `reason` stays coarse on purpose. The detail can quote the canary token the
         *     reply was discarded for, which is precisely the thing that must not travel.
         */
        Answer: {
            /**
             * Alibi Broken
             * @description The evidence caught them out. A game event, not a fault (RN-021).
             * @default false
             */
            alibi_broken: boolean;
            /** Answered */
            answered: boolean;
            /** Character */
            character: string;
            /** Line */
            line?: string | null;
            /**
             * Reason
             * @description `rejected` or `model_unavailable`, when unanswered.
             */
            reason?: string | null;
            stance?: components["schemas"]["Stance"] | null;
            /** Turns Left */
            turns_left: number;
        };
        /** CastMember */
        CastMember: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** @description How they are holding up. Absent until they have been asked. */
            stance?: components["schemas"]["Stance"] | null;
        };
        /** Confrontation */
        Confrontation: {
            /**
             * Evidence
             * @description Fact id the player holds, e.g. F-014.
             */
            evidence: string;
            /**
             * Suspect
             * @description Character id, e.g. sus-1.
             */
            suspect: string;
        };
        /**
         * DraftAccusation
         * @description The form, filled in from prose, for the player to confirm.
         *
         *     Nothing here has been committed. `POST /accusation` takes these fields back,
         *     which is what makes the confirmation structural rather than a convention:
         *     there is no way to accuse in prose.
         */
        DraftAccusation: {
            /** Culprit */
            culprit?: string | null;
            /** Culprit Name */
            culprit_name?: string | null;
            /**
             * Evidence
             * @default []
             */
            evidence: string[];
            /**
             * Evidence Text
             * @default []
             */
            evidence_text: string[];
            /** Motive */
            motive?: string | null;
            /** Motive Key */
            motive_key?: string | null;
            /**
             * Summary
             * @description The sentence to show before it counts.
             */
            summary: string;
            /**
             * Unresolved
             * @default []
             */
            unresolved: string[];
        };
        /**
         * FloorPlan
         * @description The empty board the player fills in, and nothing else.
         *
         *     Rooms and hours — never who was where. A server that handed over a filled
         *     plan would be solving the game: reconstructing the night from what people
         *     claimed *is* the deduction, so the claims stay in the answers a player has
         *     to read, and reach the plan only in the review of a finished match (RN-035).
         *
         *     Neither list is a secret. The rooms are the house and the hours are the
         *     night; the briefing already says where the body was found.
         */
        FloorPlan: {
            /** Hours */
            hours: components["schemas"]["Hour"][];
            /** Rooms */
            rooms: components["schemas"]["Room"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness probe response.
         */
        Health: {
            /**
             * Environment
             * @enum {string}
             */
            environment: "dev" | "staging" | "prod";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * HeldEvidence
         * @description A fact the player was holding by the end, and how it got there.
         */
        HeldEvidence: {
            /** Given By */
            given_by?: string | null;
            /** Given By Name */
            given_by_name?: string | null;
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Turn
             * @description Absent when it was public from the briefing.
             */
            turn?: number | null;
        };
        /** Hour */
        Hour: {
            /**
             * Interval
             * @description Index into the night, 0-based.
             */
            interval: number;
            /**
             * Label
             * @description Clock time, e.g. `22h30`.
             */
            label: string;
        };
        /** KnownFact */
        KnownFact: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /**
         * MatchState
         * @description Everything a player may see. No solution, no bookkeeping.
         */
        MatchState: {
            /** Cast */
            cast: components["schemas"]["CastMember"][];
            /**
             * Evidence
             * @description Fact ids the player holds and may present.
             * @default []
             */
            evidence: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Known */
            known: components["schemas"]["KnownFact"][];
            /**
             * Known Motives
             * @description Motives the player found out about, and may therefore name.
             * @default []
             */
            known_motives: string[];
            /** Locale */
            locale: string;
            /** Notebook */
            notebook: components["schemas"]["Said"][];
            /** @description The house and the night, empty. Constant for the match. */
            plan: components["schemas"]["FloorPlan"];
            /** Seed */
            seed: number;
            /** Turns Left */
            turns_left: number;
        };
        /**
         * NewAccusation
         * @description One per match, irreversible (RN-031). Choose carefully.
         */
        NewAccusation: {
            /**
             * Culprit
             * @description Character id you are naming.
             */
            culprit: string;
            /**
             * Evidence
             * @description Fact ids you offer in support. Only ones you hold count.
             * @default []
             */
            evidence: string[];
            /**
             * Motive Key
             * @description Why they did it. Optional — unclaimed is not wrong.
             */
            motive_key?: string | null;
        };
        /** NewMatch */
        NewMatch: {
            /**
             * Locale
             * @description Fixed for the match (ADR-0005).
             * @default pt-BR
             */
            locale: string;
            /**
             * Seed
             * @description Same seed, same mystery.
             */
            seed: number;
            /**
             * Suspects
             * @default 6
             */
            suspects: number;
        };
        /**
         * Outcome
         * @description The verdict, and the only moment the solution may cross the wire.
         *
         *     RN-011 governs a match in progress. This is its ending: the player has
         *     spent their one accusation and is owed the answer, right or wrong.
         */
        Outcome: {
            /** Accused */
            accused: string;
            /** Correct */
            correct: boolean;
            /** Culprit */
            culprit: string;
            /** Culprit Points */
            culprit_points: number;
            /**
             * Epilogue
             * @description How it ended, in prose. Absent when no model could write it — the verdict above does not depend on it (RN-032).
             */
            epilogue?: string | null;
            /** Evidence Expected */
            evidence_expected: string[];
            /** Evidence Hit */
            evidence_hit: string[];
            /** Evidence Points */
            evidence_points: number;
            /** Means */
            means: string;
            /** Motive */
            motive: string;
            /** Motive Correct */
            motive_correct: boolean;
            /** Motive Points */
            motive_points: number;
            /** Score */
            score: number;
            /** Speed Points */
            speed_points: number;
            /** Turns Left */
            turns_left: number;
        };
        /** Question */
        Question: {
            /** Question */
            question: string;
            /**
             * Suspect
             * @description Character id, e.g. sus-1.
             */
            suspect: string;
        };
        /**
         * Review
         * @description A finished match, in order, with the budget reconciled.
         *
         *     `budget`, `turns_left` and the costs in `record` add up, by construction:
         *     every turn that was charged is a row here, including the ones that produced
         *     nothing.
         */
        Review: {
            /** Budget */
            budget: number;
            /** Evidence Trail */
            evidence_trail: components["schemas"]["HeldEvidence"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Locale */
            locale: string;
            /** @description Recomputed from the record, not read from a stored copy (RN-036). The epilogue is not part of it: prose was never persisted, and its absence changes nothing about the score. */
            outcome: components["schemas"]["Outcome"];
            /** Record */
            record: components["schemas"]["ReviewedTurn"][];
            /** Seed */
            seed: number;
            /** Stance Trail */
            stance_trail: components["schemas"]["StanceMove"][];
            /** Turns Left */
            turns_left: number;
            /** Turns Spent */
            turns_spent: number;
        };
        /**
         * ReviewedTurn
         * @description One turn as the review shows it: what was asked, and what became of it.
         *
         *     This carries the bookkeeping `Said` withholds — `lied`, `fact_referenced`,
         *     `clue_revealed`. It is safe here and nowhere else, for the same reason
         *     `Outcome` may carry the solution: the match is over. A review of a match
         *     still being played would be a lie detector, so there is no such thing
         *     (RN-035).
         */
        ReviewedTurn: {
            /** Answered */
            answered: boolean;
            /** Character */
            character: string;
            /** Character Name */
            character_name: string;
            /**
             * Claimed Interval
             * @description When they said it about. An hour index from the plan.
             */
            claimed_interval?: number | null;
            /**
             * Claimed Room
             * @description Where they said they were. A room id from the plan.
             */
            claimed_room?: string | null;
            /**
             * Clue Revealed
             * @description The fact this answer gave away, if it gave one away.
             */
            clue_revealed?: string | null;
            /**
             * Cost
             * @description Turns this one cost. A confrontation costs two (RN-030).
             */
            cost: number;
            /** Fact Referenced */
            fact_referenced?: string | null;
            /**
             * Intent
             * @description How it was classified before anybody answered (RN-040).
             */
            intent: string;
            /**
             * Lied
             * @default false
             */
            lied: boolean;
            /**
             * Line
             * @description What they said. Absent when nothing was.
             */
            line?: string | null;
            /** Question */
            question: string;
            /**
             * Rejected By
             * @description Which check discarded the reply: `canary`, `scope`, `contradiction`, `refusal`. A name, never the offending text.
             */
            rejected_by?: string | null;
            /** @description The stance the turn left them in. */
            stance: components["schemas"]["Stance"];
            /** Turn */
            turn: number;
        };
        /** Room */
        Room: {
            /**
             * Id
             * @description Stable id, e.g. `study`. What a claim names.
             */
            id: string;
            /**
             * Name
             * @description How to write it in this match's language.
             */
            name: string;
        };
        /**
         * Said
         * @description One line in the notebook, as the player recorded it.
         */
        Said: {
            /** Character */
            character: string;
            /** Line */
            line: string;
            /** Question */
            question: string;
            stance: components["schemas"]["Stance"];
            /** Turn */
            turn: number;
        };
        /**
         * Stance
         * @description How a suspect is holding up. Transitions are code, never the model's call.
         *
         *     The model may suggest one; the backend validates it against the machine in
         *     `firenze.interrogation.stance` and keeps the current stance if the
         *     suggestion is not a legal move (RN-023). `broken` is absorbing and is only
         *     reachable by confrontation, which arrives in phase 4.
         * @enum {string}
         */
        Stance: "cooperative" | "evasive" | "hostile" | "broken";
        /**
         * StanceMove
         * @description A suspect changing footing, and the turn that did it.
         */
        StanceMove: {
            became: components["schemas"]["Stance"];
            /** Character */
            character: string;
            /** Character Name */
            character_name: string;
            /** Turn */
            turn: number;
            was: components["schemas"]["Stance"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    create_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accuse_matches__match_id__accusation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccusation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Outcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_accusation_matches__match_id__accusation_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccusationText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftAccusation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_confrontation_matches__match_id__confrontations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Confrontation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_matches__match_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_turn_matches__match_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Question"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
